const PLAN = [
  {
    id: 0,
    name: '1',
    day1: [
      { count: 10, done: false },
      { count: 12, done: false },
      { count: 7, done: false },
      { count: 7, done: false },
      { count: 9, done: false },
    ],
    day2: [
      { count: 10, done: false },
      { count: 12, done: false },
      { count: 8, done: false },
      { count: 8, done: false },
      { count: 12, done: false },
    ],
    day3: [
      { count: 11, done: false },
      { count: 15, done: false },
      { count: 9, done: false },
      { count: 9, done: false },
      { count: 13, done: false },
    ],
  },
  {
    id: 1,
    name: '2',
    day1: [
      { count: 14, done: false },
      { count: 14, done: false },
      { count: 10, done: false },
      { count: 10, done: false },
      { count: 15, done: false },
    ],
    day2: [
      { count: 14, done: false },
      { count: 16, done: false },
      { count: 12, done: false },
      { count: 12, done: false },
      { count: 17, done: false },
    ],
    day3: [
      { count: 16, done: false },
      { count: 17, done: false },
      { count: 14, done: false },
      { count: 14, done: false },
      { count: 20, done: false },
    ],
  },
  {
    id: 2,
    name: '3',
    day1: [
      { count: 14, done: false },
      { count: 18, done: false },
      { count: 14, done: false },
      { count: 14, done: false },
      { count: 20, done: false },
    ],
    day2: [
      { count: 20, done: false },
      { count: 25, done: false },
      { count: 15, done: false },
      { count: 15, done: false },
      { count: 25, done: false },
    ],
    day3: [
      { count: 22, done: false },
      { count: 30, done: false },
      { count: 20, done: false },
      { count: 20, done: false },
      { count: 28, done: false },
    ],
  },
  {
    id: 3,
    name: '4',
    day1: [
      { count: 21, done: false },
      { count: 25, done: false },
      { count: 21, done: false },
      { count: 21, done: false },
      { count: 32, done: false },
    ],
    day2: [
      { count: 25, done: false },
      { count: 29, done: false },
      { count: 25, done: false },
      { count: 25, done: false },
      { count: 36, done: false },
    ],
    day3: [
      { count: 29, done: false },
      { count: 33, done: false },
      { count: 29, done: false },
      { count: 29, done: false },
      { count: 40, done: false },
    ],
  },
  {
    id: 4,
    name: '5',
    day1: [
      { count: 36, done: false },
      { count: 40, done: false },
      { count: 30, done: false },
      { count: 24, done: false },
      { count: 40, done: false },
    ],
    day2: [
      { count: 19, done: false },
      { count: 19, done: false },
      { count: 22, done: false },
      { count: 22, done: false },
      { count: 18, done: false },
      { count: 18, done: false },
      { count: 22, done: false },
      { count: 45, done: false },
    ],
    day3: [
      { count: 20, done: false },
      { count: 20, done: false },
      { count: 24, done: false },
      { count: 24, done: false },
      { count: 20, done: false },
      { count: 20, done: false },
      { count: 22, done: false },
      { count: 50, done: false },
    ],
  },
  {
    id: 5,
    name: '6',
    day1: [
      { count: 45, done: false },
      { count: 55, done: false },
      { count: 35, done: false },
      { count: 30, done: false },
      { count: 55, done: false },
    ],
    day2: [
      { count: 22, done: false },
      { count: 22, done: false },
      { count: 30, done: false },
      { count: 30, done: false },
      { count: 24, done: false },
      { count: 24, done: false },
      { count: 18, done: false },
      { count: 18, done: false },
      { count: 58, done: false },
    ],
    day3: [
      { count: 26, done: false },
      { count: 26, done: false },
      { count: 33, done: false },
      { count: 33, done: false },
      { count: 26, done: false },
      { count: 26, done: false },
      { count: 22, done: false },
      { count: 22, done: false },
      { count: 60, done: false },
    ],
  },
];

export default PLAN;
